"""Materialized fact table column definitions."""

from __future__ import annotations

from mcp_strava.metric_registry_fact_column_model import FactColumnDefinition, _fact_table

MATERIALIZED_FACT_COLUMN_REGISTRY: dict[str, dict[str, FactColumnDefinition]] = {
    "activity_metric_facts": _fact_table(
        "activity_metric_facts",
        (
            ("activity_id", "dimension", ("activity_id",), "Activity identity for the materialized row."),
            ("activity_day", "dimension", ("activity_date",), "Activity day used for period and rolling filters."),
            ("sport_type", "dimension", ("sport_type",), "Sport dimension used for per-sport aggregates."),
            ("source_hash", "provenance", (), "Source mirror hash used to decide whether facts are stale."),
            ("source_revision", "provenance", (), "Monotonic source revision copied from activity_source_state."),
            ("metric_version", "provenance", (), "Read-model metric formula version."),
            ("computed_at", "provenance", (), "Timestamp when this fact row was materialized."),
            ("completeness_status", "provenance", (), "Completeness state for the source data behind this row."),
            ("missing_reasons_json", "provenance", (), "Machine-readable missing-data reasons for the row."),
            ("trimp", "metric", ("trimp",), "Per-activity TRIMP."),
            ("zone1_seconds", "dependency", ("time_in_hr_zones_min", "trimp"), "Heart-rate zone 1 seconds."),
            ("zone2_seconds", "dependency", ("time_in_hr_zones_min", "trimp"), "Heart-rate zone 2 seconds."),
            ("zone3_seconds", "dependency", ("time_in_hr_zones_min", "trimp"), "Heart-rate zone 3 seconds."),
            ("zone4_seconds", "dependency", ("time_in_hr_zones_min", "trimp"), "Heart-rate zone 4 seconds."),
            ("zone5_seconds", "dependency", ("time_in_hr_zones_min", "trimp"), "Heart-rate zone 5 seconds."),
            ("hr_recovery_pause_count", "metric", ("hr_recovery_pauses",), "Detected HR recovery pause count."),
            (
                "hr_recovery_total_rest_sec",
                "metric",
                ("hr_recovery_total_rest_sec",),
                "Total detected HR recovery rest seconds.",
            ),
            ("hr_recovery_median_rate", "metric", ("hr_recovery_median_bpm_per_min",), "Median HR recovery rate."),
            ("hr_recovery_best_rate", "metric", ("hr_recovery_best_bpm_per_min",), "Best HR recovery rate."),
            ("hr_recovery_worst_rate", "metric", ("hr_recovery_worst_bpm_per_min",), "Worst HR recovery rate."),
            ("hr_recovery_avg_rate", "metric", ("hr_recovery_avg_bpm_per_min",), "Average HR recovery rate."),
            ("vertical_speed_vmh", "metric", ("vertical_speed_m_per_h",), "Vertical speed in meters per hour."),
            (
                "vertical_speed_total_ascent_m",
                "metric",
                ("vertical_ascent_m",),
                "Positive vertical ascent used by vertical metrics.",
            ),
            (
                "vertical_speed_duration_hours",
                "metric",
                ("vertical_duration_h",),
                "Duration denominator used by vertical speed.",
            ),
            ("cardiac_cost", "metric", ("cardiac_cost",), "Per-activity cardiac cost."),
            ("adjusted_cardiac_cost", "metric", ("cardiac_cost_adjusted",), "Elevation-adjusted cardiac cost."),
            ("cardiac_drift_pct", "metric", ("cardiac_drift_pct",), "Cardiac drift percent."),
            ("cardiac_drift_severity", "metric", ("cardiac_drift_severity",), "Cardiac drift severity category."),
            ("cardiac_drift_significant", "metric", ("cardiac_drift_significant",), "Cardiac drift significant flag."),
            ("cardiac_drift_quality", "metric", ("cardiac_drift_quality",), "Cardiac drift quality category."),
            ("hrr_pct", "metric", ("hrr_pct",), "Heart-rate reserve percent."),
            ("anomaly_count", "metric", ("hr_anomaly_count",), "Heart-rate anomaly count."),
            ("distance_m", "metric", ("distance_km",), "Mirrored distance in meters."),
            ("calories_kcal", "metric", ("calories",), "Strava-reported calories in kcal (from detail_json)."),
            ("moving_time_s", "metric", ("moving_time_min",), "Mirrored moving time in seconds."),
            ("elapsed_time_s", "metric", ("elapsed_time_min",), "Mirrored elapsed time in seconds."),
            ("elevation_gain_m", "metric", ("elevation_m",), "Mirrored elevation gain in meters."),
            ("heartrate_sample_count", "dependency", ("avg_hr", "max_hr"), "Heart-rate sample denominator."),
            ("stream_sample_count", "dependency", (), "Stream sample count used for completeness checks."),
            ("observed_min_hr", "provenance", (), "Minimum heartrate sample observed in the activity streams."),
            ("observed_max_hr", "provenance", (), "Maximum heartrate sample observed in the activity streams."),
            ("hr_zone_model", "provenance", (), "HR zone model identifier used when computing zone seconds and TRIMP."),
            (
                "hr_max_used",
                "provenance",
                (),
                "Running max heartrate to date used as hr_max for zone bound computation.",
            ),
            (
                "hr_rest_used",
                "provenance",
                (),
                "Athlete resting HR from MCP_STRAVA_HR_REST used for zone bound computation.",
            ),
            (
                "start_time_local",
                "metric",
                ("start_time_local",),
                "Local time-of-day (HH:MM) the activity started, parsed from "
                "summary_json.start_date_local (fromisoformat + strftime, not a string slice).",
            ),
        ),
    ),
    "daily_load_facts": _fact_table(
        "daily_load_facts",
        (
            ("day", "dimension", ("activity_date",), "Calendar day."),
            ("scope", "dimension", (), "Aggregate scope discriminator."),
            ("sport_type", "dimension", ("sport_type",), "Sport dimension."),
            ("metric_version", "provenance", (), "Read-model metric formula version."),
            ("computed_at", "provenance", (), "Timestamp when this fact row was materialized."),
            ("completeness_status", "provenance", (), "Daily completeness state."),
            ("missing_reasons_json", "provenance", (), "Daily missing-data reasons."),
            (
                "activity_count",
                "dependency",
                ("active_days", "rest_days", "volume_7d", "volume_28d"),
                "Activity count for the day.",
            ),
            ("stream_point_count", "dependency", (), "Daily stream sample count."),
            ("heartrate_point_count", "dependency", ("avg_hr", "max_hr"), "Daily heart-rate sample count."),
            ("observed_trimp", "dependency", ("daily_trimp", "trimp"), "Observed daily TRIMP before rest-day fill."),
            (
                "effective_trimp",
                "metric",
                ("daily_trimp", "weekly_trimp", "total_trimp_14d", "avg_trimp_per_day"),
                "Effective daily load used by training model and rollups.",
            ),
            ("distance_m", "metric", ("distance_km",), "Daily distance in meters."),
            ("moving_time_s", "metric", ("moving_time_min",), "Daily moving time in seconds."),
            ("elevation_gain_m", "metric", ("elevation_m",), "Daily elevation gain in meters."),
            ("zone4_seconds", "dependency", ("time_in_hr_zones_min",), "Daily HR zone 4 seconds."),
            ("zone5_seconds", "dependency", ("time_in_hr_zones_min",), "Daily HR zone 5 seconds."),
            ("high_zone_seconds", "dependency", ("time_in_hr_zones_min",), "Daily zone 4 plus zone 5 seconds."),
            ("anomaly_count", "metric", ("hr_anomaly_count",), "Daily heart-rate anomaly count."),
        ),
    ),
    "training_model_daily": _fact_table(
        "training_model_daily",
        (
            ("day", "dimension", ("activity_date",), "Calendar day for model state."),
            ("scope", "dimension", (), "Aggregate scope discriminator."),
            ("sport_type", "dimension", ("sport_type",), "Sport dimension."),
            ("metric_version", "provenance", (), "Read-model metric formula version."),
            ("computed_at", "provenance", (), "Timestamp when this fact row was materialized."),
            ("completeness_status", "provenance", (), "Training-model completeness state."),
            ("missing_reasons_json", "provenance", (), "Training-model missing-data reasons."),
            (
                "effective_trimp",
                "dependency",
                ("fitness", "fatigue", "form", "acwr"),
                "Daily load input to the training model.",
            ),
            (
                "observed_trimp",
                "dependency",
                ("fitness", "fatigue", "form", "acwr"),
                "Observed daily load retained beside effective load.",
            ),
            ("fitness", "metric", ("fitness",), "Banister long-term fitness state."),
            ("fatigue", "metric", ("fatigue",), "Banister short-term fatigue state."),
            ("form", "metric", ("form",), "Fitness minus fatigue."),
            ("form_zone", "metric", ("form_zone",), "Agent-friendly form category."),
            ("acwr_zone", "metric", ("acwr_zone",), "Agent-friendly ACWR category."),
            ("acwr", "metric", ("acwr",), "Acute chronic workload ratio."),
            ("load_7d", "dependency", ("fatigue",), "Short-horizon model load retained for model provenance."),
            ("load_28d", "dependency", (), "Medium-horizon model load slot retained for model provenance."),
            ("load_42d", "dependency", ("fitness",), "Long-horizon model load retained for model provenance."),
            ("input_days", "provenance", (), "Number of input days used for model materialization."),
            ("missing_days", "provenance", (), "Number of missing model input days."),
        ),
    ),
    "rolling_period_facts": _fact_table(
        "rolling_period_facts",
        (
            ("as_of_day", "dimension", ("activity_date",), "Inclusive rolling-window end day."),
            ("window_days", "dimension", (), "Rolling window width in days."),
            ("scope", "dimension", (), "Aggregate scope discriminator."),
            ("sport_type", "dimension", ("sport_type",), "Sport dimension."),
            ("metric_version", "provenance", (), "Read-model metric formula version."),
            ("computed_at", "provenance", (), "Timestamp when this fact row was materialized."),
            ("completeness_status", "provenance", (), "Rolling-window completeness state."),
            ("missing_reasons_json", "provenance", (), "Rolling-window missing-data reasons."),
            ("activity_count", "metric", ("volume_7d", "volume_28d"), "Activity count in the rolling window."),
            ("active_days", "metric", ("active_days",), "Active days in the rolling window."),
            ("rest_days", "metric", ("rest_days",), "Rest days in the rolling window."),
            ("observed_trimp", "dependency", ("trimp",), "Observed TRIMP sum in the rolling window."),
            (
                "effective_trimp",
                "metric",
                (
                    "weekly_trimp",
                    "total_trimp_14d",
                    "avg_trimp_per_day",
                    "daily_avg_trimp_7d",
                    "daily_avg_trimp_28d",
                    "daily_avg_trimp_90d",
                ),
                "Effective TRIMP sum in the rolling window.",
            ),
            ("distance_m", "metric", ("distance_km",), "Distance sum in meters."),
            ("moving_time_s", "metric", ("moving_time_min",), "Moving-time sum in seconds."),
            ("elevation_gain_m", "metric", ("elevation_m",), "Elevation-gain sum in meters."),
            (
                "high_zone_seconds",
                "dependency",
                ("time_in_hr_zones_min",),
                "High HR-zone seconds in the rolling window.",
            ),
            ("anomaly_count", "metric", ("hr_anomaly_count",), "Heart-rate anomaly count in the rolling window."),
            ("fitness", "metric", ("fitness",), "Latest fitness state at the rolling as-of day."),
            ("fatigue", "metric", ("fatigue",), "Latest fatigue state at the rolling as-of day."),
            ("form", "metric", ("form",), "Latest form state at the rolling as-of day."),
            ("form_zone", "metric", ("form_zone",), "Latest form-zone state at the rolling as-of day."),
            ("acwr_zone", "metric", ("acwr_zone",), "Latest ACWR-zone state at the rolling as-of day."),
            ("acwr", "metric", ("acwr",), "Latest ACWR at the rolling as-of day."),
            ("median_cardiac_cost", "metric", ("rolling_median_cc",), "Rolling median cardiac cost."),
            (
                "median_adjusted_cardiac_cost",
                "metric",
                ("rolling_median_cc_adj",),
                "Rolling median adjusted cardiac cost.",
            ),
            ("median_hr_recovery", "metric", ("rolling_median_hr_recovery",), "Rolling median HR recovery."),
            (
                "median_cardiac_drift_pct",
                "metric",
                ("rolling_median_cardiac_drift_pct",),
                "Rolling median cardiac drift percent.",
            ),
        ),
    ),
}
