"""Activity metric definitions."""

from __future__ import annotations

from mcp_strava.metric_registry_metric_factory import _metric
from mcp_strava.types import MetricDefinition

ACTIVITY_METRICS: dict[str, MetricDefinition] = {
    "activity_id": _metric(
        "activity_id",
        "Activity ID",
        "id",
        "activity",
        "activity",
        "both",
        "none",
        "neutral",
        ["list_workouts", "get_workout_detail"],
    ),
    "activity_date": _metric(
        "activity_date",
        "Activity Date",
        "date",
        "activity",
        "activity",
        "both",
        "none",
        "neutral",
        ["list_workouts", "get_workout_detail"],
    ),
    "sport_type": _metric(
        "sport_type",
        "Sport Type",
        "category",
        "activity",
        "activity",
        "both",
        "distribution",
        "neutral",
        ["list_workouts", "get_workout_detail"],
    ),
    "activity_name": _metric(
        "activity_name",
        "Activity Name",
        "text",
        "activity",
        "activity",
        "both",
        "none",
        "neutral",
        ["list_workouts", "get_workout_detail"],
    ),
    "kudos_count": _metric(
        "kudos_count",
        "Kudos Count",
        "count",
        "activity",
        "activity",
        "both",
        "none",
        "context",
        ["list_workouts", "get_workout_detail"],
    ),
    "kudos_names": _metric(
        "kudos_names",
        "Kudos Names",
        "text_list",
        "activity",
        "activity",
        "both",
        "none",
        "context",
        ["get_workout_detail"],
    ),
    "gear_id": _metric(
        "gear_id", "Gear ID", "id", "activity", "activity", "both", "none", "context", ["get_workout_detail"]
    ),
    "gear_name": _metric(
        "gear_name", "Gear Name", "text", "activity", "activity", "both", "none", "context", ["get_workout_detail"]
    ),
    "gear_distance_km": _metric(
        "gear_distance_km",
        "Gear Distance",
        "km",
        "activity",
        "activity",
        "both",
        "none",
        "context",
        ["get_workout_detail"],
    ),
    "gear_primary": _metric(
        "gear_primary",
        "Primary Gear",
        "boolean",
        "activity",
        "activity",
        "both",
        "none",
        "context",
        ["get_workout_detail"],
    ),
    "distance_km": _metric(
        "distance_km",
        "Distance",
        "km",
        "activity",
        "activity",
        "both",
        "sum",
        "higher_is_more",
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "calories": _metric(
        "calories",
        "Calories",
        "kcal",
        "activity",
        "activity",
        "both",
        "sum",
        "higher_is_more",
        ["compare_periods"],
    ),
    "moving_time_min": _metric(
        "moving_time_min",
        "Moving Time",
        "minutes",
        "activity",
        "activity",
        "both",
        "sum",
        "higher_is_more",
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "elapsed_time_min": _metric(
        "elapsed_time_min",
        "Elapsed Time",
        "minutes",
        "activity",
        "activity",
        "both",
        "sum",
        "higher_is_more",
        ["get_workout_detail", "compare_periods"],
    ),
    "elevation_m": _metric(
        "elevation_m",
        "Elevation Gain",
        "m",
        "activity",
        "activity",
        "both",
        "sum",
        "higher_is_more",
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "start_time_local": _metric(
        "start_time_local",
        "Start Time",
        "time",
        "activity",
        "activity",
        "both",
        "none",
        "neutral",
        ["list_workouts", "get_workout_detail"],
    ),
    "relative_time": _metric(
        "relative_time",
        "Relative Time",
        "text",
        "activity",
        "activity",
        "both",
        "none",
        "context",
        ["list_workouts", "get_workout_detail"],
    ),
    "trimp": _metric(
        "trimp",
        "TRIMP",
        "trimp",
        "activity",
        "activity",
        "global",
        "sum",
        "higher_is_more",
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "avg_hr": _metric(
        "avg_hr",
        "Average Heart Rate",
        "bpm",
        "activity",
        "activity",
        "per_sport",
        "avg",
        "context",
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "max_hr": _metric(
        "max_hr",
        "Max Heart Rate",
        "bpm",
        "activity",
        "activity",
        "per_sport",
        "max",
        "higher_is_more",
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "time_in_hr_zones_min": _metric(
        "time_in_hr_zones_min",
        "Time In HR Zones",
        "minutes",
        "activity",
        "activity",
        "both",
        "distribution",
        "context",
        ["get_workout_detail", "compare_periods"],
    ),
}
