"""Training metric definitions."""

from __future__ import annotations

from mcp_strava.metric_registry_metric_factory import _metric
from mcp_strava.types import MetricDefinition

TRAINING_METRICS: dict[str, MetricDefinition] = {
    "fitness": _metric(
        "fitness",
        "Fitness",
        "model_units",
        "training",
        "model",
        "global",
        "last",
        "higher_is_more",
        ["get_fitness_state", "compare_periods"],
    ),
    "fatigue": _metric(
        "fatigue",
        "Fatigue",
        "model_units",
        "training",
        "model",
        "global",
        "last",
        "higher_is_more",
        ["get_fitness_state", "compare_periods"],
    ),
    "form": _metric(
        "form",
        "Form",
        "model_units",
        "training",
        "model",
        "global",
        "last",
        "higher_is_more",
        ["get_fitness_state", "compare_periods"],
    ),
    "form_zone": _metric(
        "form_zone", "Form Zone", "category", "training", "model", "global", "none", "context", ["get_fitness_state"]
    ),
    "banister_history": _metric(
        "banister_history", "Banister History", "model_units", "training", "period", "global", "trend", "context", []
    ),
    "progressive_load_bonus": _metric(
        "progressive_load_bonus",
        "Progressive Load Bonus",
        "ratio",
        "training",
        "model",
        "global",
        "last",
        "higher_is_more",
        [],
    ),
    "progressive_cc_trends": _metric(
        "progressive_cc_trends",
        "Progressive CC Trends",
        "percent",
        "training",
        "model",
        "per_sport",
        "trend",
        "lower_is_better",
        [],
    ),
    "projected_daily_trimp": _metric(
        "projected_daily_trimp",
        "Projected Daily TRIMP",
        "trimp",
        "training",
        "projection",
        "global",
        "distribution",
        "context",
        ["project_fitness_state"],
    ),
    "projected_fitness": _metric(
        "projected_fitness",
        "Projected Fitness",
        "model_units",
        "training",
        "projection",
        "global",
        "last",
        "higher_is_more",
        ["project_fitness_state"],
    ),
    "projected_fatigue": _metric(
        "projected_fatigue",
        "Projected Fatigue",
        "model_units",
        "training",
        "projection",
        "global",
        "last",
        "higher_is_more",
        ["project_fitness_state"],
    ),
    "projected_form": _metric(
        "projected_form",
        "Projected Form",
        "model_units",
        "training",
        "projection",
        "global",
        "last",
        "higher_is_more",
        ["project_fitness_state"],
    ),
    "target_date_form": _metric(
        "target_date_form",
        "Target Date Form",
        "model_units",
        "training",
        "projection",
        "global",
        "last",
        "higher_is_more",
        ["project_fitness_state"],
    ),
    "post_weekend_monday_form": _metric(
        "post_weekend_monday_form",
        "Post Weekend Monday Form",
        "model_units",
        "training",
        "projection",
        "global",
        "distribution",
        "higher_is_more",
        ["project_fitness_state"],
    ),
    "activity_template_trimp": _metric(
        "activity_template_trimp",
        "Activity Template TRIMP",
        "trimp",
        "training",
        "projection",
        "global",
        "distribution",
        "context",
        ["project_fitness_state"],
    ),
}
