"""Activity metric definitions."""

from __future__ import annotations

from mcp_strava.metric_registry_metric_factory import _metric
from mcp_strava.metric_registry_specs import MetricSpec
from mcp_strava.types import MetricDefinition

ACTIVITY_METRICS: dict[str, MetricDefinition] = {
    "activity_id": _metric(
        "activity_id",
        MetricSpec(
            label="Activity ID",
            unit="id",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="neutral",
        ),
        ["list_workouts", "get_workout_detail"],
    ),
    "activity_date": _metric(
        "activity_date",
        MetricSpec(
            label="Activity Date",
            unit="date",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="neutral",
        ),
        ["list_workouts", "get_workout_detail"],
    ),
    "sport_type": _metric(
        "sport_type",
        MetricSpec(
            label="Sport Type",
            unit="category",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="distribution",
            directionality="neutral",
        ),
        ["list_workouts", "get_workout_detail"],
    ),
    "activity_name": _metric(
        "activity_name",
        MetricSpec(
            label="Activity Name",
            unit="text",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="neutral",
        ),
        ["list_workouts", "get_workout_detail"],
    ),
    "kudos_count": _metric(
        "kudos_count",
        MetricSpec(
            label="Kudos Count",
            unit="count",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="context",
        ),
        ["list_workouts", "get_workout_detail"],
    ),
    "kudos_names": _metric(
        "kudos_names",
        MetricSpec(
            label="Kudos Names",
            unit="text_list",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="context",
        ),
        ["get_workout_detail"],
    ),
    "gear_id": _metric(
        "gear_id",
        MetricSpec(
            label="Gear ID",
            unit="id",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="context",
        ),
        ["get_workout_detail"],
    ),
    "gear_name": _metric(
        "gear_name",
        MetricSpec(
            label="Gear Name",
            unit="text",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="context",
        ),
        ["get_workout_detail"],
    ),
    "gear_distance_km": _metric(
        "gear_distance_km",
        MetricSpec(
            label="Gear Distance",
            unit="km",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="context",
        ),
        ["get_workout_detail"],
    ),
    "gear_primary": _metric(
        "gear_primary",
        MetricSpec(
            label="Primary Gear",
            unit="boolean",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="context",
        ),
        ["get_workout_detail"],
    ),
    "distance_km": _metric(
        "distance_km",
        MetricSpec(
            label="Distance",
            unit="km",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="sum",
            directionality="higher_is_more",
        ),
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "calories": _metric(
        "calories",
        MetricSpec(
            label="Calories",
            unit="kcal",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="sum",
            directionality="higher_is_more",
        ),
        ["compare_periods"],
    ),
    "moving_time_min": _metric(
        "moving_time_min",
        MetricSpec(
            label="Moving Time",
            unit="minutes",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="sum",
            directionality="higher_is_more",
        ),
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "elapsed_time_min": _metric(
        "elapsed_time_min",
        MetricSpec(
            label="Elapsed Time",
            unit="minutes",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="sum",
            directionality="higher_is_more",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "elevation_m": _metric(
        "elevation_m",
        MetricSpec(
            label="Elevation Gain",
            unit="m",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="sum",
            directionality="higher_is_more",
        ),
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "start_time_local": _metric(
        "start_time_local",
        MetricSpec(
            label="Start Time",
            unit="time",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="neutral",
        ),
        ["list_workouts", "get_workout_detail"],
    ),
    "relative_time": _metric(
        "relative_time",
        MetricSpec(
            label="Relative Time",
            unit="text",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="none",
            directionality="context",
        ),
        ["list_workouts", "get_workout_detail"],
    ),
    "trimp": _metric(
        "trimp",
        MetricSpec(
            label="TRIMP",
            unit="trimp",
            source="activity",
            scope="activity",
            sport_scope="global",
            comparison_mode="sum",
            directionality="higher_is_more",
        ),
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "avg_hr": _metric(
        "avg_hr",
        MetricSpec(
            label="Average Heart Rate",
            unit="bpm",
            source="activity",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="avg",
            directionality="context",
        ),
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "max_hr": _metric(
        "max_hr",
        MetricSpec(
            label="Max Heart Rate",
            unit="bpm",
            source="activity",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="max",
            directionality="higher_is_more",
        ),
        ["list_workouts", "get_workout_detail", "compare_periods"],
    ),
    "time_in_hr_zones_min": _metric(
        "time_in_hr_zones_min",
        MetricSpec(
            label="Time In HR Zones",
            unit="minutes",
            source="activity",
            scope="activity",
            sport_scope="both",
            comparison_mode="distribution",
            directionality="context",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
}
