"""Materialized fact-column SQL metadata."""

from __future__ import annotations

_SUPPORTED_FACT_SQL_TYPES = frozenset({"BIGINT", "DOUBLE", "VARCHAR", "DATE", "BOOLEAN", "VARCHAR[]"})


_SUPPORTED_FACT_DEFAULT_SQL = frozenset({"0", "0.0", "'[]'", "[]"})


def _sql(sql_type: str, *, nullable: bool = True, default_sql: str | None = None) -> tuple[str, bool, str | None]:
    return sql_type, nullable, default_sql


_MATERIALIZED_FACT_COLUMN_SQL_METADATA: dict[str, dict[str, tuple[str, bool, str | None]]] = {
    "activity_metric_facts": {
        "activity_id": _sql("BIGINT", nullable=False),
        "activity_day": _sql("DATE", nullable=False),
        "sport_type": _sql("VARCHAR", nullable=False),
        "source_hash": _sql("VARCHAR", nullable=False),
        "source_revision": _sql("BIGINT", nullable=False),
        "metric_version": _sql("BIGINT", nullable=False),
        "computed_at": _sql("VARCHAR", nullable=False),
        "completeness_status": _sql("VARCHAR", nullable=False),
        "missing_reasons_json": _sql("VARCHAR[]", nullable=False, default_sql="[]"),
        "trimp": _sql("DOUBLE"),
        "zone1_seconds": _sql("BIGINT", nullable=False, default_sql="0"),
        "zone2_seconds": _sql("BIGINT", nullable=False, default_sql="0"),
        "zone3_seconds": _sql("BIGINT", nullable=False, default_sql="0"),
        "zone4_seconds": _sql("BIGINT", nullable=False, default_sql="0"),
        "zone5_seconds": _sql("BIGINT", nullable=False, default_sql="0"),
        "hr_recovery_pause_count": _sql("BIGINT", nullable=False, default_sql="0"),
        "hr_recovery_total_rest_sec": _sql("BIGINT", nullable=False, default_sql="0"),
        "hr_recovery_median_rate": _sql("DOUBLE"),
        "hr_recovery_best_rate": _sql("DOUBLE"),
        "hr_recovery_worst_rate": _sql("DOUBLE"),
        "hr_recovery_avg_rate": _sql("DOUBLE"),
        "vertical_speed_vmh": _sql("BIGINT"),
        "vertical_speed_total_ascent_m": _sql("DOUBLE"),
        "vertical_speed_duration_hours": _sql("DOUBLE"),
        "cardiac_cost": _sql("DOUBLE"),
        "adjusted_cardiac_cost": _sql("DOUBLE"),
        "cardiac_drift_pct": _sql("DOUBLE"),
        "cardiac_drift_severity": _sql("VARCHAR"),
        "cardiac_drift_significant": _sql("BOOLEAN", nullable=False, default_sql="0"),
        "cardiac_drift_quality": _sql("VARCHAR"),
        "hrr_pct": _sql("DOUBLE"),
        "anomaly_count": _sql("BIGINT", nullable=False, default_sql="0"),
        "distance_m": _sql("DOUBLE"),
        "calories_kcal": _sql("DOUBLE"),
        "moving_time_s": _sql("BIGINT"),
        "elapsed_time_s": _sql("BIGINT"),
        "elevation_gain_m": _sql("DOUBLE"),
        "heartrate_sample_count": _sql("BIGINT", nullable=False, default_sql="0"),
        "stream_sample_count": _sql("BIGINT", nullable=False, default_sql="0"),
        "observed_min_hr": _sql("BIGINT"),
        "observed_max_hr": _sql("BIGINT"),
        "hr_zone_model": _sql("VARCHAR"),
        "hr_max_used": _sql("BIGINT"),
        "hr_rest_used": _sql("BIGINT"),
        "start_time_local": _sql("VARCHAR"),
    },
    "daily_load_facts": {
        "day": _sql("DATE", nullable=False),
        "scope": _sql("VARCHAR", nullable=False),
        "sport_type": _sql("VARCHAR", nullable=False),
        "metric_version": _sql("BIGINT", nullable=False),
        "computed_at": _sql("VARCHAR", nullable=False),
        "completeness_status": _sql("VARCHAR", nullable=False),
        "missing_reasons_json": _sql("VARCHAR[]", nullable=False, default_sql="[]"),
        "activity_count": _sql("BIGINT", nullable=False, default_sql="0"),
        "stream_point_count": _sql("BIGINT", nullable=False, default_sql="0"),
        "heartrate_point_count": _sql("BIGINT", nullable=False, default_sql="0"),
        "observed_trimp": _sql("DOUBLE"),
        "effective_trimp": _sql("DOUBLE", nullable=False, default_sql="0.0"),
        "distance_m": _sql("DOUBLE", nullable=False, default_sql="0.0"),
        "moving_time_s": _sql("BIGINT", nullable=False, default_sql="0"),
        "elevation_gain_m": _sql("DOUBLE", nullable=False, default_sql="0.0"),
        "zone4_seconds": _sql("BIGINT", nullable=False, default_sql="0"),
        "zone5_seconds": _sql("BIGINT", nullable=False, default_sql="0"),
        "high_zone_seconds": _sql("BIGINT", nullable=False, default_sql="0"),
        "anomaly_count": _sql("BIGINT", nullable=False, default_sql="0"),
    },
    "training_model_daily": {
        "day": _sql("DATE", nullable=False),
        "scope": _sql("VARCHAR", nullable=False),
        "sport_type": _sql("VARCHAR", nullable=False),
        "metric_version": _sql("BIGINT", nullable=False),
        "computed_at": _sql("VARCHAR", nullable=False),
        "completeness_status": _sql("VARCHAR", nullable=False),
        "missing_reasons_json": _sql("VARCHAR[]", nullable=False, default_sql="[]"),
        "effective_trimp": _sql("DOUBLE", nullable=False, default_sql="0.0"),
        "observed_trimp": _sql("DOUBLE"),
        "fitness": _sql("DOUBLE"),
        "fatigue": _sql("DOUBLE"),
        "form": _sql("DOUBLE"),
        "form_zone": _sql("VARCHAR"),
        "acwr_zone": _sql("VARCHAR"),
        "acwr": _sql("DOUBLE"),
        "load_7d": _sql("DOUBLE"),
        "load_28d": _sql("DOUBLE"),
        "load_42d": _sql("DOUBLE"),
        "input_days": _sql("BIGINT", nullable=False, default_sql="0"),
        "missing_days": _sql("BIGINT", nullable=False, default_sql="0"),
    },
    "rolling_period_facts": {
        "as_of_day": _sql("DATE", nullable=False),
        "window_days": _sql("BIGINT", nullable=False),
        "scope": _sql("VARCHAR", nullable=False),
        "sport_type": _sql("VARCHAR", nullable=False),
        "metric_version": _sql("BIGINT", nullable=False),
        "computed_at": _sql("VARCHAR", nullable=False),
        "completeness_status": _sql("VARCHAR", nullable=False),
        "missing_reasons_json": _sql("VARCHAR[]", nullable=False, default_sql="[]"),
        "activity_count": _sql("BIGINT", nullable=False, default_sql="0"),
        "active_days": _sql("BIGINT", nullable=False, default_sql="0"),
        "rest_days": _sql("BIGINT", nullable=False, default_sql="0"),
        "observed_trimp": _sql("DOUBLE"),
        "effective_trimp": _sql("DOUBLE", nullable=False, default_sql="0.0"),
        "distance_m": _sql("DOUBLE", nullable=False, default_sql="0.0"),
        "moving_time_s": _sql("BIGINT", nullable=False, default_sql="0"),
        "elevation_gain_m": _sql("DOUBLE", nullable=False, default_sql="0.0"),
        "high_zone_seconds": _sql("BIGINT", nullable=False, default_sql="0"),
        "anomaly_count": _sql("BIGINT", nullable=False, default_sql="0"),
        "fitness": _sql("DOUBLE"),
        "fatigue": _sql("DOUBLE"),
        "form": _sql("DOUBLE"),
        "form_zone": _sql("VARCHAR"),
        "acwr_zone": _sql("VARCHAR"),
        "acwr": _sql("DOUBLE"),
        "median_cardiac_cost": _sql("DOUBLE"),
        "median_adjusted_cardiac_cost": _sql("DOUBLE"),
        "median_hr_recovery": _sql("DOUBLE"),
        "median_cardiac_drift_pct": _sql("DOUBLE"),
    },
}
