"""Analytics metric definitions."""

from __future__ import annotations

from mcp_strava.metric_registry_metric_factory import _metric
from mcp_strava.types import MetricDefinition

ANALYTICS_METRICS: dict[str, MetricDefinition] = {
    "daily_avg_trimp_7d": _metric(
        "daily_avg_trimp_7d",
        "Daily Average TRIMP 7d",
        "trimp",
        "analytics",
        "period",
        "global",
        "avg",
        "higher_is_more",
        ["get_fitness_state", "compare_periods"],
    ),
    "daily_avg_trimp_28d": _metric(
        "daily_avg_trimp_28d",
        "Daily Average TRIMP 28d",
        "trimp",
        "analytics",
        "period",
        "global",
        "avg",
        "higher_is_more",
        ["get_fitness_state", "compare_periods"],
    ),
    "daily_avg_trimp_90d": _metric(
        "daily_avg_trimp_90d",
        "Daily Average TRIMP 90d",
        "trimp",
        "analytics",
        "period",
        "global",
        "avg",
        "higher_is_more",
        ["get_fitness_state", "compare_periods"],
    ),
    "rolling_median_cc": _metric(
        "rolling_median_cc",
        "Rolling Median Cardiac Cost",
        "ratio",
        "analytics",
        "period",
        "per_sport",
        "median",
        "lower_is_better",
        ["get_fitness_state", "compare_periods"],
    ),
    "rolling_median_cc_adj": _metric(
        "rolling_median_cc_adj",
        "Rolling Median Adjusted Cardiac Cost",
        "ratio",
        "analytics",
        "period",
        "per_sport",
        "median",
        "lower_is_better",
        ["get_fitness_state", "compare_periods"],
    ),
    "rolling_median_epkm": _metric(
        "rolling_median_epkm",
        "Rolling Median Elevation Per KM",
        "m_per_km",
        "analytics",
        "period",
        "per_sport",
        "median",
        "context",
        [],
    ),
    "rolling_median_hr_recovery": _metric(
        "rolling_median_hr_recovery",
        "Rolling Median HR Recovery",
        "bpm_per_min",
        "analytics",
        "period",
        "per_sport",
        "median",
        "higher_is_better",
        ["get_fitness_state", "compare_periods"],
    ),
    "rolling_median_cardiac_drift_pct": _metric(
        "rolling_median_cardiac_drift_pct",
        "Rolling Median Cardiac Drift",
        "percent",
        "analytics",
        "period",
        "per_sport",
        "median",
        "lower_is_better",
        ["get_fitness_state", "compare_periods"],
    ),
    "volume_7d": _metric(
        "volume_7d",
        "Volume 7d",
        "count",
        "analytics",
        "period",
        "global",
        "sum",
        "higher_is_more",
        ["get_fitness_state", "compare_periods"],
    ),
    "volume_28d": _metric(
        "volume_28d",
        "Volume 28d",
        "count",
        "analytics",
        "period",
        "global",
        "sum",
        "higher_is_more",
        ["get_fitness_state", "compare_periods"],
    ),
    "load_trend_pct": _metric(
        "load_trend_pct", "Load Trend", "percent", "analytics", "period", "global", "trend", "higher_is_more", []
    ),
    "efficiency_trend_pct": _metric(
        "efficiency_trend_pct",
        "Efficiency Trend",
        "percent",
        "analytics",
        "period",
        "per_sport",
        "trend",
        "lower_is_better",
        [],
    ),
    "run_90d_median_cc_trend_pct": _metric(
        "run_90d_median_cc_trend_pct",
        "Run 90d Median CC Trend",
        "percent",
        "analytics",
        "period",
        "per_sport",
        "trend",
        "lower_is_better",
        [],
    ),
    "activity_streak_days": _metric(
        "activity_streak_days",
        "Activity Streak",
        "count",
        "analytics",
        "period",
        "global",
        "last",
        "higher_is_more",
        [],
    ),
    "rest_streak_days": _metric(
        "rest_streak_days", "Rest Streak", "count", "analytics", "period", "global", "last", "higher_is_more", []
    ),
    "last_hike_days_ago": _metric(
        "last_hike_days_ago",
        "Last Hike Days Ago",
        "count",
        "analytics",
        "period",
        "global",
        "last",
        "lower_is_recent",
        [],
    ),
}
