"""Analytics metric definitions."""

from __future__ import annotations

from mcp_strava.metric_registry_metric_factory import _metric
from mcp_strava.metric_registry_specs import MetricSpec
from mcp_strava.types import MetricDefinition

ANALYTICS_METRICS: dict[str, MetricDefinition] = {
    "daily_avg_trimp_7d": _metric(
        "daily_avg_trimp_7d",
        MetricSpec(
            label="Daily Average TRIMP 7d",
            unit="trimp",
            source="analytics",
            scope="period",
            sport_scope="global",
            comparison_mode="avg",
            directionality="higher_is_more",
        ),
        ["get_fitness_state", "compare_periods"],
    ),
    "daily_avg_trimp_28d": _metric(
        "daily_avg_trimp_28d",
        MetricSpec(
            label="Daily Average TRIMP 28d",
            unit="trimp",
            source="analytics",
            scope="period",
            sport_scope="global",
            comparison_mode="avg",
            directionality="higher_is_more",
        ),
        ["get_fitness_state", "compare_periods"],
    ),
    "daily_avg_trimp_90d": _metric(
        "daily_avg_trimp_90d",
        MetricSpec(
            label="Daily Average TRIMP 90d",
            unit="trimp",
            source="analytics",
            scope="period",
            sport_scope="global",
            comparison_mode="avg",
            directionality="higher_is_more",
        ),
        ["get_fitness_state", "compare_periods"],
    ),
    "rolling_median_cc": _metric(
        "rolling_median_cc",
        MetricSpec(
            label="Rolling Median Cardiac Cost",
            unit="ratio",
            source="analytics",
            scope="period",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="lower_is_better",
        ),
        ["get_fitness_state", "compare_periods"],
    ),
    "rolling_median_cc_adj": _metric(
        "rolling_median_cc_adj",
        MetricSpec(
            label="Rolling Median Adjusted Cardiac Cost",
            unit="ratio",
            source="analytics",
            scope="period",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="lower_is_better",
        ),
        ["get_fitness_state", "compare_periods"],
    ),
    "rolling_median_epkm": _metric(
        "rolling_median_epkm",
        MetricSpec(
            label="Rolling Median Elevation Per KM",
            unit="m_per_km",
            source="analytics",
            scope="period",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="context",
        ),
        [],
    ),
    "rolling_median_hr_recovery": _metric(
        "rolling_median_hr_recovery",
        MetricSpec(
            label="Rolling Median HR Recovery",
            unit="bpm_per_min",
            source="analytics",
            scope="period",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="higher_is_better",
        ),
        ["get_fitness_state", "compare_periods"],
    ),
    "rolling_median_cardiac_drift_pct": _metric(
        "rolling_median_cardiac_drift_pct",
        MetricSpec(
            label="Rolling Median Cardiac Drift",
            unit="percent",
            source="analytics",
            scope="period",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="lower_is_better",
        ),
        ["get_fitness_state", "compare_periods"],
    ),
    "volume_7d": _metric(
        "volume_7d",
        MetricSpec(
            label="Volume 7d",
            unit="count",
            source="analytics",
            scope="period",
            sport_scope="global",
            comparison_mode="sum",
            directionality="higher_is_more",
        ),
        ["get_fitness_state", "compare_periods"],
    ),
    "volume_28d": _metric(
        "volume_28d",
        MetricSpec(
            label="Volume 28d",
            unit="count",
            source="analytics",
            scope="period",
            sport_scope="global",
            comparison_mode="sum",
            directionality="higher_is_more",
        ),
        ["get_fitness_state", "compare_periods"],
    ),
    "load_trend_pct": _metric(
        "load_trend_pct",
        MetricSpec(
            label="Load Trend",
            unit="percent",
            source="analytics",
            scope="period",
            sport_scope="global",
            comparison_mode="trend",
            directionality="higher_is_more",
        ),
        [],
    ),
    "efficiency_trend_pct": _metric(
        "efficiency_trend_pct",
        MetricSpec(
            label="Efficiency Trend",
            unit="percent",
            source="analytics",
            scope="period",
            sport_scope="per_sport",
            comparison_mode="trend",
            directionality="lower_is_better",
        ),
        [],
    ),
    "run_90d_median_cc_trend_pct": _metric(
        "run_90d_median_cc_trend_pct",
        MetricSpec(
            label="Run 90d Median CC Trend",
            unit="percent",
            source="analytics",
            scope="period",
            sport_scope="per_sport",
            comparison_mode="trend",
            directionality="lower_is_better",
        ),
        [],
    ),
    "activity_streak_days": _metric(
        "activity_streak_days",
        MetricSpec(
            label="Activity Streak",
            unit="count",
            source="analytics",
            scope="period",
            sport_scope="global",
            comparison_mode="last",
            directionality="higher_is_more",
        ),
        [],
    ),
    "rest_streak_days": _metric(
        "rest_streak_days",
        MetricSpec(
            label="Rest Streak",
            unit="count",
            source="analytics",
            scope="period",
            sport_scope="global",
            comparison_mode="last",
            directionality="higher_is_more",
        ),
        [],
    ),
    "last_hike_days_ago": _metric(
        "last_hike_days_ago",
        MetricSpec(
            label="Last Hike Days Ago",
            unit="count",
            source="analytics",
            scope="period",
            sport_scope="global",
            comparison_mode="last",
            directionality="lower_is_recent",
        ),
        [],
    ),
}
