"""Metrics metric definitions."""

from __future__ import annotations

from mcp_strava.metric_registry_metric_factory import _metric
from mcp_strava.types import MetricDefinition

STREAM_METRICS: dict[str, MetricDefinition] = {
    "hr_recovery_pauses": _metric(
        "hr_recovery_pauses",
        "HR Recovery Pauses",
        "count",
        "metrics",
        "activity",
        "per_sport",
        "sum",
        "context",
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_recovery_total_rest_sec": _metric(
        "hr_recovery_total_rest_sec",
        "HR Recovery Rest Time",
        "seconds",
        "metrics",
        "activity",
        "per_sport",
        "sum",
        "context",
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_recovery_median_bpm_per_min": _metric(
        "hr_recovery_median_bpm_per_min",
        "HR Recovery Median",
        "bpm_per_min",
        "metrics",
        "activity",
        "per_sport",
        "median",
        "higher_is_better",
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_recovery_best_bpm_per_min": _metric(
        "hr_recovery_best_bpm_per_min",
        "HR Recovery Best",
        "bpm_per_min",
        "metrics",
        "activity",
        "per_sport",
        "max",
        "higher_is_better",
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_recovery_worst_bpm_per_min": _metric(
        "hr_recovery_worst_bpm_per_min",
        "HR Recovery Worst",
        "bpm_per_min",
        "metrics",
        "activity",
        "per_sport",
        "min",
        "higher_is_worse",
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_recovery_avg_bpm_per_min": _metric(
        "hr_recovery_avg_bpm_per_min",
        "HR Recovery Average",
        "bpm_per_min",
        "metrics",
        "activity",
        "per_sport",
        "avg",
        "higher_is_better",
        ["get_workout_detail", "compare_periods"],
    ),
    "vertical_speed_m_per_h": _metric(
        "vertical_speed_m_per_h",
        "Vertical Speed",
        "m_per_hour",
        "metrics",
        "activity",
        "per_sport",
        "median",
        "higher_is_more",
        ["get_workout_detail", "compare_periods"],
    ),
    "vertical_ascent_m": _metric(
        "vertical_ascent_m",
        "Vertical Ascent",
        "m",
        "metrics",
        "activity",
        "both",
        "sum",
        "higher_is_more",
        ["get_workout_detail", "compare_periods"],
    ),
    "vertical_duration_h": _metric(
        "vertical_duration_h",
        "Vertical Duration",
        "hours",
        "metrics",
        "activity",
        "both",
        "sum",
        "higher_is_more",
        ["get_workout_detail", "compare_periods"],
    ),
    "cardiac_cost": _metric(
        "cardiac_cost",
        "Cardiac Cost",
        "ratio",
        "metrics",
        "activity",
        "per_sport",
        "median",
        "lower_is_better",
        ["get_workout_detail", "compare_periods"],
    ),
    "cardiac_cost_adjusted": _metric(
        "cardiac_cost_adjusted",
        "Cardiac Cost Adjusted",
        "ratio",
        "metrics",
        "activity",
        "per_sport",
        "median",
        "lower_is_better",
        ["get_workout_detail", "compare_periods"],
    ),
    "cardiac_drift_pct": _metric(
        "cardiac_drift_pct",
        "Cardiac Drift",
        "percent",
        "metrics",
        "activity",
        "per_sport",
        "median",
        "lower_is_better",
        ["get_workout_detail", "compare_periods"],
    ),
    "cardiac_drift_severity": _metric(
        "cardiac_drift_severity",
        "Cardiac Drift Severity",
        "category",
        "metrics",
        "activity",
        "per_sport",
        "distribution",
        "context",
        ["get_workout_detail"],
    ),
    "cardiac_drift_significant": _metric(
        "cardiac_drift_significant",
        "Cardiac Drift Significant",
        "count",
        "metrics",
        "activity",
        "per_sport",
        "sum",
        "higher_is_worse",
        ["get_workout_detail", "compare_periods"],
    ),
    "cardiac_drift_quality": _metric(
        "cardiac_drift_quality",
        "Cardiac Drift Quality",
        "category",
        "metrics",
        "activity",
        "per_sport",
        "distribution",
        "context",
        ["get_workout_detail"],
    ),
    "hrr_pct": _metric(
        "hrr_pct",
        "HRR Percent",
        "percent",
        "metrics",
        "activity",
        "per_sport",
        "median",
        "lower_is_easier",
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_anomaly_count": _metric(
        "hr_anomaly_count",
        "HR Anomaly Count",
        "count",
        "metrics",
        "activity",
        "both",
        "sum",
        "higher_is_worse",
        ["get_workout_detail", "compare_periods"],
    ),
}
