"""Metric definition factory and calculation descriptions."""

from __future__ import annotations

from mcp_strava.types import MetricDefinition

_DEFAULT_REQUIREMENTS = ["metric_available_from_local_mirror"]
_DEFAULT_MISSING_REASONS = ["not_available_in_source", "insufficient_samples"]
_CALCULATION_BY_METRIC_ID = {
    "activity_id": "Direct Strava activity id stored in activities.id.",
    "activity_date": "Local activity day derived from the stored Strava activity start date.",
    "sport_type": "Direct Strava sport_type stored on the activity row.",
    "activity_name": "Direct Strava activity name stored on the activity row.",
    "kudos_count": "Strava summary_json.kudos_count for the activity, defaulting to 0 when Strava omitted it.",
    "kudos_names": "Names stored from the Strava kudos endpoint for the activity, grouped by activity_id and formatted from firstname and lastname.",
    "gear_id": "Strava gear id copied from the activity summary or detail payload when mirrored for an activity.",
    "gear_name": "Gear or shoe display name copied from the detailed Strava gear payload when it is mirrored for an activity.",
    "gear_distance_km": "Total mirrored Strava gear distance in meters divided by 1000 when the detailed gear payload provides distance.",
    "gear_primary": "Boolean primary-gear flag copied from the detailed Strava gear payload when Strava marks a shoe as primary.",
    "distance_km": "Activity distance_m from the mirror divided by 1000.",
    "calories": "Strava's reported calories (kcal) per activity, summed over the period.",
    "moving_time_min": "Activity moving_time_s from the mirror divided by 60.",
    "elapsed_time_min": "Activity elapsed_time_s from the mirror divided by 60.",
    "elevation_m": "Activity total elevation gain in meters from the mirrored Strava activity.",
    "start_time_local": "Local time-of-day (HH:MM) the activity started, parsed from "
    "summary_json.start_date_local via fromisoformat + strftime (not a string slice); "
    "materialized on the activity fact row.",
    "relative_time": "Human recency of the activity relative to now, computed at read time "
    "from start_date_local: '<H>h <M>m' under 24h, '<N>d <H>h' from one day on.",
    "trimp": "Per-activity TRIMP = sum(seconds in each HR zone * zone weight) / 60 using the configured HR zone model and athlete resting HR.",
    "avg_hr": "Strava summary_json.average_heartrate for the activity.",
    "max_hr": "Strava summary_json.max_heartrate rounded to an integer bpm.",
    "time_in_hr_zones_min": "Counts stream heartrate samples in the five configured HR zones and divides seconds by 60.",
    "hr_recovery_pauses": "Count of detected rest pauses from HR recovery analysis; pauses are >= Config.Metrics.MIN_PAUSE_SEC with velocity < Config.Thresholds.VEL_STOP.",
    "hr_recovery_total_rest_sec": "Total seconds across detected HR recovery rest pauses.",
    "hr_recovery_median_bpm_per_min": "Median HR drop rate across detected rest pauses, in bpm per minute.",
    "hr_recovery_best_bpm_per_min": "Maximum HR drop rate across detected rest pauses, in bpm per minute.",
    "hr_recovery_worst_bpm_per_min": "Minimum HR drop rate across detected rest pauses, in bpm per minute.",
    "hr_recovery_avg_bpm_per_min": "Arithmetic mean HR drop rate across detected rest pauses, in bpm per minute.",
    "vertical_speed_m_per_h": "Positive altitude gain from altitude stream divided by elapsed stream duration in hours.",
    "vertical_ascent_m": "Sum of positive altitude deltas from the altitude stream.",
    "vertical_duration_h": "Elapsed stream duration used for vertical speed, computed from the last stream time_offset / 3600.",
    "cardiac_cost": "Average stream heartrate divided by average stream velocity for points above Config.Thresholds.VEL_MOVING.",
    "cardiac_cost_adjusted": "Elevation-adjusted cardiac cost = cardiac_cost - Config.Efficiency.CC_ELEV_COEFF * elevation_gain_m_per_km.",
    "cardiac_drift_pct": "Jenks-clusters moving stream velocity into pace bands, compares early vs late median HR inside bands, and returns weighted HR drift percent.",
    "cardiac_drift_severity": "Cardiac drift severity label from the Jenks-based algorithm: stable, borderline, moderate, significant, or severe.",
    "cardiac_drift_significant": "Boolean activity flag materialized as 1 when the cardiac drift algorithm marks the drift significant, otherwise 0.",
    "cardiac_drift_quality": "Cardiac drift algorithm quality label based on clustered data duration: good, fair, or low.",
    "hrr_pct": "(median_hr - athlete_hr_rest) / (observed_hr_max - athlete_hr_rest) * 100, using MCP_STRAVA_HR_REST.",
    "hr_anomaly_count": "Count of consecutive stream heartrate jumps greater than 30 bpm.",
    "daily_trimp": "Daily effective TRIMP series from daily_load_facts, using observed TRIMP on complete HR days and 0 for rest or unknown days.",
    "total_trimp_14d": "Sum of effective_trimp over the 14-day rolling window ending at the query day.",
    "avg_trimp_per_day": "total_trimp_14d divided by 14.",
    "active_days": "Count of days with activity_count > 0 in the 14-day rolling window.",
    "rest_days": "Count of days with activity_count = 0 in the 14-day rolling window.",
    "weekly_trimp": "Sum of effective_trimp over the 7-day rolling window ending at the query day.",
    "by_sport_trimp": "Period TRIMP grouped by sport from enriched activity/report rows.",
    "by_sport_distance_km": "Period distance grouped by sport from mirrored activity distance_m divided by 1000.",
    "by_sport_time_min": "Period moving time grouped by sport from mirrored moving_time_s divided by 60.",
    "by_sport_elevation_m": "Period elevation gain grouped by sport from mirrored elevation_gain_m.",
    "fitness": "Banister long-term fitness EWMA of daily effective_trimp using Config.Model.Banister.TAU_FITNESS.",
    "fatigue": "Banister short-term fatigue EWMA of daily effective_trimp using Config.Model.Banister.TAU_FATIGUE.",
    "form": "Banister form = fitness - fatigue.",
    "form_zone": "Agent-friendly form category: tired when form < -5, normal when -5 <= form < 10, fresh when form >= 10.",
    "banister_history": "Daily Banister time series of fitness, fatigue, form, form_zone, and TRIMP for recent/report windows.",
    "acwr": "Acute:chronic workload ratio stored as fatigue / fitness when fitness > 0.",
    "acwr_zone": "Agent-friendly ACWR category: sweet_spot for 0.8-1.3, caution up to Config.Thresholds.ACWR_DANGER, danger above it, undertrained below 0.8.",
    "acwr_history": "Daily ACWR time series with the fatigue and fitness inputs used for each point.",
    "daily_avg_trimp_7d": "7-day rolling effective_trimp sum divided by 7.",
    "daily_avg_trimp_28d": "28-day rolling effective_trimp sum divided by 28.",
    "daily_avg_trimp_90d": "90-day rolling effective_trimp sum divided by 90.",
    "rolling_median_cc": "Rolling median cardiac_cost from materialized activity_metric_facts for the selected window.",
    "rolling_median_cc_adj": "Rolling median cardiac_cost_adjusted from materialized activity_metric_facts for the selected window.",
    "rolling_median_epkm": "Rolling median elevation gain per kilometer from per-activity analytics rows.",
    "rolling_median_hr_recovery": "Rolling median hr_recovery_median_bpm_per_min from materialized activity_metric_facts for the selected window.",
    "rolling_median_cardiac_drift_pct": "Rolling median cardiac_drift_pct from materialized activity_metric_facts for the selected window.",
    "volume_7d": "Activity count over the 7-day rolling window.",
    "volume_28d": "Activity count over the 28-day rolling window.",
    "load_trend_pct": "Percent change of rolling daily TRIMP load between the current window and the previous equally sized window.",
    "efficiency_trend_pct": "Percent change of per-sport rolling cardiac efficiency metrics, especially median cardiac cost.",
    "run_90d_median_cc_trend_pct": "Percent change of 90-day running median cardiac cost versus the previous 90-day running window.",
    "activity_streak_days": "Count of consecutive recent days with at least one activity.",
    "rest_streak_days": "Count of consecutive recent days without activity.",
    "last_hike_days_ago": "Days since the latest mirrored Hike activity.",
    "progressive_load_bonus": "Progressive-overload scalar from 21-day quality trends; positive when quality improves, negative when fatigue signals worsen.",
    "progressive_cc_trends": "Per-sport cardiac-cost trend bundle used by the progressive signal calculation.",
    "projected_daily_trimp": "Scenario input TRIMP for each projected day: rest=0, easy=Config.Plan.TRIMP_EASY, maintain=recent weekday pattern, custom=user input.",
    "projected_fitness": "Forward-simulated Banister fitness from current baseline and projected_daily_trimp.",
    "projected_fatigue": "Forward-simulated Banister fatigue from current baseline and projected_daily_trimp.",
    "projected_form": "Forward-simulated projected_fitness - projected_fatigue.",
    "target_date_form": "The final projected_form value on the requested target_date for a scenario.",
    "post_weekend_monday_form": "When target_date is Friday-Sunday, forward-simulates rest days after target_date and reports the following Monday form.",
    "activity_template_trimp": "Scenario template TRIMP value, currently Config.Plan.TRIMP_EASY for the easy scenario.",
}


def _metric(
    metric_id: str,
    label: str,
    unit: str,
    source: str,
    scope: str,
    sport_scope: str,
    comparison_mode: str,
    directionality: str,
    exposed_in: list[str],
    description: str = "",
    calculation: str | None = None,
    requirements: list[str] | None = None,
    missing_reasons: list[str] | None = None,
) -> MetricDefinition:
    calculation_text = calculation or _CALCULATION_BY_METRIC_ID.get(metric_id, "")
    if not calculation_text:
        raise ValueError(f"Missing calculation description for metric: {metric_id}")
    return MetricDefinition(
        metric_id=metric_id,
        label=label,
        unit=unit,
        source=source,
        scope=scope,
        sport_scope=sport_scope,
        comparison_mode=comparison_mode,
        directionality=directionality,
        requirements=list(requirements or _DEFAULT_REQUIREMENTS),
        missing_reasons=list(missing_reasons or _DEFAULT_MISSING_REASONS),
        exposed_in=exposed_in,
        calculation=calculation_text,
        description=description,
    )
