"""Metrics metric definitions."""

from __future__ import annotations

from mcp_strava.metric_registry_metric_factory import _metric
from mcp_strava.metric_registry_specs import MetricSpec
from mcp_strava.types import MetricDefinition

STREAM_METRICS: dict[str, MetricDefinition] = {
    "hr_recovery_pauses": _metric(
        "hr_recovery_pauses",
        MetricSpec(
            label="HR Recovery Pauses",
            unit="count",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="sum",
            directionality="context",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_recovery_total_rest_sec": _metric(
        "hr_recovery_total_rest_sec",
        MetricSpec(
            label="HR Recovery Rest Time",
            unit="seconds",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="sum",
            directionality="context",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_recovery_median_bpm_per_min": _metric(
        "hr_recovery_median_bpm_per_min",
        MetricSpec(
            label="HR Recovery Median",
            unit="bpm_per_min",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="higher_is_better",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_recovery_best_bpm_per_min": _metric(
        "hr_recovery_best_bpm_per_min",
        MetricSpec(
            label="HR Recovery Best",
            unit="bpm_per_min",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="max",
            directionality="higher_is_better",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_recovery_worst_bpm_per_min": _metric(
        "hr_recovery_worst_bpm_per_min",
        MetricSpec(
            label="HR Recovery Worst",
            unit="bpm_per_min",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="min",
            directionality="higher_is_worse",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_recovery_avg_bpm_per_min": _metric(
        "hr_recovery_avg_bpm_per_min",
        MetricSpec(
            label="HR Recovery Average",
            unit="bpm_per_min",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="avg",
            directionality="higher_is_better",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "vertical_speed_m_per_h": _metric(
        "vertical_speed_m_per_h",
        MetricSpec(
            label="Vertical Speed",
            unit="m_per_hour",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="higher_is_more",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "vertical_ascent_m": _metric(
        "vertical_ascent_m",
        MetricSpec(
            label="Vertical Ascent",
            unit="m",
            source="metrics",
            scope="activity",
            sport_scope="both",
            comparison_mode="sum",
            directionality="higher_is_more",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "vertical_duration_h": _metric(
        "vertical_duration_h",
        MetricSpec(
            label="Vertical Duration",
            unit="hours",
            source="metrics",
            scope="activity",
            sport_scope="both",
            comparison_mode="sum",
            directionality="higher_is_more",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "cardiac_cost": _metric(
        "cardiac_cost",
        MetricSpec(
            label="Cardiac Cost",
            unit="ratio",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="lower_is_better",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "cardiac_cost_adjusted": _metric(
        "cardiac_cost_adjusted",
        MetricSpec(
            label="Cardiac Cost Adjusted",
            unit="ratio",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="lower_is_better",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "cardiac_drift_pct": _metric(
        "cardiac_drift_pct",
        MetricSpec(
            label="Cardiac Drift",
            unit="percent",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="lower_is_better",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "cardiac_drift_severity": _metric(
        "cardiac_drift_severity",
        MetricSpec(
            label="Cardiac Drift Severity",
            unit="category",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="distribution",
            directionality="context",
        ),
        ["get_workout_detail"],
    ),
    "cardiac_drift_significant": _metric(
        "cardiac_drift_significant",
        MetricSpec(
            label="Cardiac Drift Significant",
            unit="count",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="sum",
            directionality="higher_is_worse",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "cardiac_drift_quality": _metric(
        "cardiac_drift_quality",
        MetricSpec(
            label="Cardiac Drift Quality",
            unit="category",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="distribution",
            directionality="context",
        ),
        ["get_workout_detail"],
    ),
    "hrr_pct": _metric(
        "hrr_pct",
        MetricSpec(
            label="HRR Percent",
            unit="percent",
            source="metrics",
            scope="activity",
            sport_scope="per_sport",
            comparison_mode="median",
            directionality="lower_is_easier",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
    "hr_anomaly_count": _metric(
        "hr_anomaly_count",
        MetricSpec(
            label="HR Anomaly Count",
            unit="count",
            source="metrics",
            scope="activity",
            sport_scope="both",
            comparison_mode="sum",
            directionality="higher_is_worse",
        ),
        ["get_workout_detail", "compare_periods"],
    ),
}
