"""Data contracts shared across Strava mirror, metrics, refresh, and services."""

from __future__ import annotations

from mcp_strava.types_activity_metrics import (
    CardiacDriftResult,
    DecouplingResult,
    EnrichedActivity,
    HrRecovery,
    VerticalSpeed,
)
from mcp_strava.types_registry import ExcludedInterpretation, MetricDefinition, StatusFact, StatusFactDefinition
from mcp_strava.types_repository import (
    ALLOWED_REASON_CODES,
    ActivityMetricFact,
    ActivitySourceState,
    DailyLoadFact,
    DailyLoadPoint,
    DailyLoadStatus,
    MetricDirtyActivity,
    ReadModelRefreshRun,
    RefreshRequestRow,
    RefreshStateRow,
    RepositoryActivityRow,
    RepositorySyncLogEntry,
    RollingPeriodFact,
    TrainingModelDailyFact,
)
from mcp_strava.types_serialization import dc_to_dict, smart_round
from mcp_strava.types_service import (
    CompletenessMetadata,
    FreshnessMetadata,
    ReadModelMetadata,
    ServiceEnvelope,
    ServiceRationale,
    ServiceWarning,
)
from mcp_strava.types_strava import (
    StravaActivity,
    StravaAthlete,
    StravaShoe,
    StravaStreamChannel,
    StravaStreams,
    StreamChannelMetadata,
    parse_strava_activity,
    parse_strava_athlete,
    parse_strava_stream_channels,
    parse_strava_streams,
)
from mcp_strava.types_training import BanisterResult, SimDay

__all__ = [
    "ALLOWED_REASON_CODES",
    "ActivityMetricFact",
    "ActivitySourceState",
    "BanisterResult",
    "CardiacDriftResult",
    "CompletenessMetadata",
    "DailyLoadFact",
    "DailyLoadPoint",
    "DailyLoadStatus",
    "DecouplingResult",
    "EnrichedActivity",
    "ExcludedInterpretation",
    "FreshnessMetadata",
    "HrRecovery",
    "MetricDefinition",
    "MetricDirtyActivity",
    "ReadModelMetadata",
    "ReadModelRefreshRun",
    "RefreshRequestRow",
    "RefreshStateRow",
    "RepositoryActivityRow",
    "RepositorySyncLogEntry",
    "RollingPeriodFact",
    "ServiceEnvelope",
    "ServiceRationale",
    "ServiceWarning",
    "SimDay",
    "StatusFact",
    "StatusFactDefinition",
    "StravaActivity",
    "StravaAthlete",
    "StravaShoe",
    "StravaStreamChannel",
    "StravaStreams",
    "StreamChannelMetadata",
    "TrainingModelDailyFact",
    "VerticalSpeed",
    "dc_to_dict",
    "parse_strava_activity",
    "parse_strava_athlete",
    "parse_strava_stream_channels",
    "parse_strava_streams",
    "smart_round",
]
